---
title: "Test NPSShallowLakes"
author: "SDMiller"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NPSShallowLakes)
library(odbc)
```

# Test NPSShallowLakes

## GetDatabaseConnection

```{r}
# Get a connection to the AK_ShallowLakes database
Connection = GetDatabaseConnection()
print(Connection)

# Execute the query against the database using the database connection above
DF = odbc::dbGetQuery(Connection,'SELECT Top 3 PONDNAME FROM tblPonds')
knitr::kable(DF)
```

## GetLakeCoordinatesTable

```{r}
# Get a data frame of spatial coordinates for Lake YUCH-004
LakeCoordinates = GetLakeCoordinatesTable('YUCH-004')
head(LakeCoordinates)
```

## GetLakeMap

```{r}
# Get a Leaflet map showing Lake YUCH-004
GetLakeMap('YUCH-004',15)
```


## GetWaterProfilePlotForLake

```{r}
# Example of use:
GetWaterProfilePlotForLake('BELA-033','DO_Pct')
GetWaterProfilePlotForLake('YUCH-004','Temperature')
```

# Scratch

```{r}
  # Load the leaflet library
  library(leaflet)
  library(odbc)
Lake='YUCH-004'
ZoomLevel=13
  # Try to open a database connection to the AK_ShallowLakes database

    #Connect to the AK_ShallowLakes database
    Connection = GetDatabaseConnection()

    # Get the data using the odbc method
    Sql = paste("SELECT PONDNAME
,CASE WHEN M_LAT_WGS84 IS NULL And M_LAT_NAD83 IS NOT NULL THEN M_LAT_NAD83 ELSE M_LAT_WGS84 END As Lat
,CASE WHEN M_LON_WGS84 IS NULL And M_LON_NAD83 IS NOT NULL THEN M_LON_NAD83 ELSE M_LON_WGS84 END As Lon
, M_ELEVATION
FROM tblMonuments
WHERE (PONDNAME = '",Lake,"')",sep="")
    DF = odbc::dbGetQuery(Connection,Sql)

    # Map the units in Leaflet
    map = leaflet() %>%
      # Set the view and zoom levels
      setView(lng = DF$Lon, lat = DF$Lat, zoom = ZoomLevel) %>%
      # Add WMS tiles
      addWMSTiles('https://basemap.nationalmap.gov:443/arcgis/services/USGSTopo/MapServer/WmsServer',layers = "0",options = WMSTileOptions(format = "image/png")) %>%

      # Label the units
      addLabelOnlyMarkers(~Lon,~Lat, label = ~PONDNAME, data = DF,  labelOptions = labelOptions(noHide = TRUE))
map
```













